modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="catchandtame"
version="1.0.0"
displayName="Catch And Tame"
updateJSONURL=""
displayURL=""
logoFile=""
credits="Violet"
authors="Violet"
description='''
Allows you to catch and tame any entity.
'''

[[dependencies.catchandtame]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.catchandtame]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
